FROM ternarypulsar/opam-test-base
USER root
RUN opam install alcotest-lwt angstrom async base64 bls12-381.0.4.3 bls12-381-unix.0.4.3 ca-certs camlzip.1.10 data-encoding digestif fmt ipaddr ipaddr-sexp irmin irmin-pack hacl hacl-star jsonm logs lwt.5.4.1 lwt-dllist.1.0.1 lwt-canceler.0.3 lwt-exit lwt-watcher.0.1 lwt_log lwt_ssl magic-mime ppx_deriving ppx_sexp_conv ppx_inline_test.v0.14.1 ppxlib re resto-cohttp.0.6 resto-cohttp-server.0.6 ringo ringo-lwt.0.5 secp256k1-internal sexplib sexplib0 stringext tar.1.1.0 tar-unix.1.1.0 tls ocp-ocamlres.0.4 zarith.1.11
