v0_srcs = [
    "v0/s.ml",
    "v0/option.ml",
    "v0/mBytes.ml",
    "v0/blake2B.ml",
    "v0/ed25519.ml",
    "v0/secp256k1.ml",
    "v0/p256.ml",
    "v0/signature.ml",
    "v0/chain_id.ml",
    "v0/block_hash.ml",
    "v0/operation_hash.ml",
    "v0/operation_list_hash.ml",
    "v0/operation_list_list_hash.ml",
    "v0/protocol_hash.ml",
    "v0/context_hash.ml",
    "v0/error_monad_traversors.ml",
    "v0/data_encoding.ml",
]

v1_srcs = [
    "v1/s.ml",
    "v1/blake2B.ml",
    "v1/ed25519.ml",
    "v1/secp256k1.ml",
    "v1/p256.ml",
    "v1/signature.ml",
    "v1/chain_id.ml",
    "v1/block_hash.ml",
    "v1/operation_hash.ml",
    "v1/operation_list_hash.ml",
    "v1/operation_list_list_hash.ml",
    "v1/protocol_hash.ml",
    "v1/context_hash.ml",
    "v1/error_monad_traversors.ml",
    "v1/option.ml",
    "v1/data_encoding.ml",
]

v2_srcs = [
    "v2/s.ml",
    "v2/blake2B.ml",
    "v2/ed25519.ml",
    "v2/secp256k1.ml",
    "v2/p256.ml",
    "v2/signature.ml",
    "v2/chain_id.ml",
    "v2/block_hash.ml",
    "v2/operation_hash.ml",
    "v2/operation_list_hash.ml",
    "v2/operation_list_list_hash.ml",
    "v2/protocol_hash.ml",
    "v2/context_hash.ml",
    "v2/error_monad_traversors.ml",
    "v2/data_encoding.ml",
]

v3_srcs = [
    "v3/s.ml",
    "v3/blake2B.ml",
    "v3/ed25519.ml",
    "v3/secp256k1.ml",
    "v3/p256.ml",
    "v3/signature.ml",
    "v3/chain_id.ml",
    "v3/block_hash.ml",
    "v3/operation_hash.ml",
    "v3/operation_list_hash.ml",
    "v3/operation_list_list_hash.ml",
    "v3/protocol_hash.ml",
    "v3/context_hash.ml",
    "v3/error_monad_traversors.ml",
]
